### ISSUE TITLE
.tablereg file parallelization

### ISSUE THREAD

**Issue by mitchwagner** [Glavin001/FAdo#3]
Hi there,

When using FAdo, I noticed it left a file, ".tablereg", in the directory I ran my script from. I'm unsure how this file is used, and whether or not it will cause issues if I run multiple jobs in parallel from the same directory.

Would you be willing to provide insight as to the purpose of this file and whether or not this is safe?

Thanks!

**Comment by Glavin001** [comment]
Hi!

Unfortunately, I do not officially support or maintain this project. It is actually a fork I used for a school project and extended some small functionality. The vast majority of code was developed by the maintainers of https://pypi.python.org/pypi/FAdo , including the code you are asking about.

However, I took a look and here is what I found:
- Where `.tablereg` is used: https://github.com/Glavin001/FAdo/blob/32d5cec89fd31ff88b2a65484d6fe16b778052dd/reex.py#L1802-L1823
- Which leads me to https://github.com/Glavin001/FAdo/blob/32d5cec89fd31ff88b2a65484d6fe16b778052dd/yappy_parser.py#L1787-L1797

It appears the `.tablereg` is used as a "parse table" for `LRparser`.

I do see checks to verify the parent directory exists, however not much more: https://github.com/Glavin001/FAdo/blob/32d5cec89fd31ff88b2a65484d6fe16b778052dd/yappy_parser.py#L1806-L1807

I think it would likely impact multiple jobs run in parallel from the same directory. You should contact the maintainers of https://pypi.python.org/pypi/FAdo or experiment on your own.

Best of luck! 😃

**Comment by mitchwagner** [comment]
Sorry for the misunderstanding, and thank you very much for your assistance!
